In [2]:
import torch

In [55]:
x = torch.rand(3,5)
x = torch.empty(1,2)
x = torch.zeros(2,2,2,dtype = torch.long)
x = torch.tensor([[1,3],[0,7]])

# print(type(x[0][0][0]))
print(x)

tensor([[-0.0000, 1.9980]])


In [31]:
print(x[0][0])

tensor(1)


In [38]:
x = x.new_ones(4,3)
print(x)
x = torch.ones(5,1)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [46]:
x = torch.randn_like(x, dtype=torch.float32)
print(x)

tensor([[-0.5722],
        [ 0.6958],
        [ 2.1319],
        [-0.2526],
        [ 0.8522]])


In [49]:
print(x.size())
print(type(x.size()))

torch.Size([5, 1])
<class 'torch.Size'>


In [59]:
x = torch.ones(5,3)
print(x)
y = torch.rand(5,3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5650, 0.9895, 0.4245],
        [0.2851, 0.2725, 0.8853],
        [0.4373, 0.7161, 0.0280],
        [0.0733, 0.9449, 0.0458],
        [0.6091, 0.9963, 0.8438]])


In [60]:
print(x+y)

tensor([[1.5650, 1.9895, 1.4245],
        [1.2851, 1.2725, 1.8853],
        [1.4373, 1.7161, 1.0280],
        [1.0733, 1.9449, 1.0458],
        [1.6091, 1.9963, 1.8438]])


In [61]:
print(torch.add(x,y))
print(torch.add(x,y) == (x+y))

tensor([[1.5650, 1.9895, 1.4245],
        [1.2851, 1.2725, 1.8853],
        [1.4373, 1.7161, 1.0280],
        [1.0733, 1.9449, 1.0458],
        [1.6091, 1.9963, 1.8438]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


In [62]:
print(y)
print(x)
y.add_(x)
print(y)

tensor([[0.5650, 0.9895, 0.4245],
        [0.2851, 0.2725, 0.8853],
        [0.4373, 0.7161, 0.0280],
        [0.0733, 0.9449, 0.0458],
        [0.6091, 0.9963, 0.8438]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.5650, 1.9895, 1.4245],
        [1.2851, 1.2725, 1.8853],
        [1.4373, 1.7161, 1.0280],
        [1.0733, 1.9449, 1.0458],
        [1.6091, 1.9963, 1.8438]])


In [66]:
y.t_()
print(y)

tensor([[1.5650, 1.2851, 1.4373, 1.0733, 1.6091],
        [1.9895, 1.2725, 1.7161, 1.9449, 1.9963],
        [1.4245, 1.8853, 1.0280, 1.0458, 1.8438]])


In [68]:
print(y[:,0])

tensor([1.5650, 1.9895, 1.4245])


In [81]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x,y,z,sep = '\n')

tensor([[ 2.7120,  0.7249, -0.2495,  1.0278],
        [ 0.0945, -1.9900, -1.4022,  0.0554],
        [ 0.7581,  2.3782, -0.4054,  2.5092],
        [ 3.0157,  1.3365,  0.7028,  0.1493]])
tensor([ 2.7120,  0.7249, -0.2495,  1.0278,  0.0945, -1.9900, -1.4022,  0.0554,
         0.7581,  2.3782, -0.4054,  2.5092,  3.0157,  1.3365,  0.7028,  0.1493])
tensor([[ 2.7120,  0.7249, -0.2495,  1.0278,  0.0945, -1.9900, -1.4022,  0.0554],
        [ 0.7581,  2.3782, -0.4054,  2.5092,  3.0157,  1.3365,  0.7028,  0.1493]])


In [82]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0486])
1.048575520515442


In [84]:
a = torch.ones(10)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [89]:
b = a.numpy()
print(b)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [90]:
a.add_(1)
print(a)
# b.add_(1)
print(b)

tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


In [91]:
import numpy as np 
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [102]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(type(device))
    
    y = torch.ones_like(x, device = device)
    print(y)
    x = x.to(device)
    print(x)
    z = x + y
    print(z)
    z = z.to("cpu", torch.int)
    print(z)

<class 'torch.device'>
tensor([1.], device='cuda:0')
tensor([1.0486], device='cuda:0')
tensor([2.0486], device='cuda:0')
tensor([2], dtype=torch.int32)
