In [1]:
import torch

In [3]:
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[108., 108.],
        [108., 108.]], grad_fn=<MulBackward0>) tensor(108., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[-2.7230,  7.4023],
        [ 1.5770,  7.4000]])
True


In [11]:
print(out)

tensor(108., grad_fn=<MeanBackward0>)


In [12]:
out.backward()

In [17]:
print(out)
print(x)
print(x.grad)

tensor(108., grad_fn=<MeanBackward0>)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[9., 9.],
        [9., 9.]])


In [20]:
x = torch.randn(3, requires_grad = True)

y = x * 2
print(y)
print(y.grad_fn)
while y.data.norm() <1000:
    y = y * 2
print(y)
print(y.grad_fn)

tensor([-3.8608, -2.5636, -1.9171], grad_fn=<MulBackward0>)
tensor([-988.3592, -656.2709, -490.7852], grad_fn=<MulBackward0>)


In [21]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradients)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [23]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
